### ISSUE TITLE
Namespace management

### ISSUE THREAD

**Issue by wpjunior** [backstage/functions#1]
All functions in this service should belongs in a namespace, it's useful to organize and do better ownership of functions.

**Comment by pedrosnk** [comment]
The thing about this tasks I believe is define the routes of the functions

The better way to define that is making all the routes in a rest way in a way that this should be the url of the resource

`/functions/:namespace/:function_name`

and to run the function call this route

`/functions/:namespace/:funtion_name/run`

**Comment by heitorsilva** [comment]
@wpjunior finished with commit 	7101de8
